'use client';
import { useState } from 'react';
import { assetSequence } from '../../content-data';
import { Header, Footer } from '../../site-shell';

export default function SequencesPage() {
  const [enabled, setEnabled] = useState([true, true, true, true]);
  const [paused, setPaused] = useState(false);
  return <main><Header /><section className="admin-shell shell"><div className="admin-heading"><div><p className="eyebrow">Sequence manager</p><h1>Teach first. Branch later.</h1><p className="lede">Edit the shared sequence, switch individual steps off, or pause the whole nurture safely. Changes here are local demo state until persistence and an email provider are connected.</p></div><button className={`pause-button ${paused ? 'is-paused' : ''}`} onClick={() => setPaused((value) => !value)}>{paused ? 'Resume nurture' : 'Pause all sends'}</button></div><div className="sequence-list">{assetSequence.map((asset, index) => <article className={`sequence-card ${enabled[index] && !paused ? '' : 'disabled'}`} key={asset.key}><div className="sequence-number">{String(asset.number).padStart(2, '0')}</div><div><p className="eyebrow">Asset {asset.number}{asset.number === 4 ? ' · branch point' : ''}</p><h2>{asset.title}</h2><p>{asset.description}</p><div className="sequence-meta"><span>Subject: {['Start with the funnel foundation', 'Make the message match', 'Your next helpful follow-up', 'Choose the right funnel path'][index]}</span><span>Delay: {index === 0 ? 'Immediate' : `${index} day${index > 1 ? 's' : ''}`}</span></div></div><label className="step-toggle"><span>{enabled[index] ? 'Enabled' : 'Disabled'}</span><input type="checkbox" checked={enabled[index]} onChange={() => setEnabled((items) => items.map((value, itemIndex) => itemIndex === index ? !value : value))} /></label></article>)}</div><div className="branch-card"><div><p className="eyebrow">Asset 4 routing</p><h2>Segment answers select nurture and recommendation.</h2><p>Shared assets remain the default. Once a lead selects a business type, the engine adds a segment tag, enrolls the matching branch, and selects the configured ClickFunnels offer candidate.</p></div><div className="branch-pills"><span>Coaching → 3 Months for $99</span><span>Course → Funnel Builder Secrets</span><span>Agency → 3 Months for $99</span><span>Unknown → Free Trial</span></div></div></section><Footer /></main>; }
